//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.04 at 07:08:01 PM GMT 
//


package net.leadware.drools.server.model.configuration;

/*
 * #%L
 * DROOLS SERVER :: Model
 * $Id:$
 * $HeadURL:$
 * %%
 * Copyright (C) 2013 - 2014 Leadware
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for KnowledgeSessionConfiguration complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="KnowledgeSessionConfiguration">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="knowledge-base-ref" type="{http://www.leadware.net/drools-server-configuration}KnowledgeBaseConfigurationRef"/>
 *         &lt;element name="knowledge-agent-ref" type="{http://www.leadware.net/drools-server-configuration}KnowledgeAgentConfigurationRef"/>
 *       &lt;/choice>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="type" type="{http://www.leadware.net/drools-server-configuration}KnowledgeSessionTypeConfiguration" default="STATELESS" />
 *       &lt;attribute name="debug" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "KnowledgeSessionConfiguration", namespace = "http://www.leadware.net/drools-server-configuration", propOrder = {
    "knowledgeBaseRef",
    "knowledgeAgentRef"
})
public class KnowledgeSessionConfiguration {

    @XmlElement(name = "knowledge-base-ref", namespace = "http://www.leadware.net/drools-server-configuration")
    protected KnowledgeBaseConfigurationRef knowledgeBaseRef;
    @XmlElement(name = "knowledge-agent-ref", namespace = "http://www.leadware.net/drools-server-configuration")
    protected KnowledgeAgentConfigurationRef knowledgeAgentRef;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "type")
    protected KnowledgeSessionTypeConfiguration type;
    @XmlAttribute(name = "debug")
    protected Boolean debug;

    /**
     * Gets the value of the knowledgeBaseRef property.
     * 
     * @return
     *     possible object is
     *     {@link KnowledgeBaseConfigurationRef }
     *     
     */
    public KnowledgeBaseConfigurationRef getKnowledgeBaseRef() {
        return knowledgeBaseRef;
    }

    /**
     * Sets the value of the knowledgeBaseRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link KnowledgeBaseConfigurationRef }
     *     
     */
    public void setKnowledgeBaseRef(KnowledgeBaseConfigurationRef value) {
        this.knowledgeBaseRef = value;
    }

    /**
     * Gets the value of the knowledgeAgentRef property.
     * 
     * @return
     *     possible object is
     *     {@link KnowledgeAgentConfigurationRef }
     *     
     */
    public KnowledgeAgentConfigurationRef getKnowledgeAgentRef() {
        return knowledgeAgentRef;
    }

    /**
     * Sets the value of the knowledgeAgentRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link KnowledgeAgentConfigurationRef }
     *     
     */
    public void setKnowledgeAgentRef(KnowledgeAgentConfigurationRef value) {
        this.knowledgeAgentRef = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link KnowledgeSessionTypeConfiguration }
     *     
     */
    public KnowledgeSessionTypeConfiguration getType() {
        if (type == null) {
            return KnowledgeSessionTypeConfiguration.STATELESS;
        } else {
            return type;
        }
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link KnowledgeSessionTypeConfiguration }
     *     
     */
    public void setType(KnowledgeSessionTypeConfiguration value) {
        this.type = value;
    }

    /**
     * Gets the value of the debug property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isDebug() {
        if (debug == null) {
            return false;
        } else {
            return debug;
        }
    }

    /**
     * Sets the value of the debug property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDebug(Boolean value) {
        this.debug = value;
    }

}
