//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.31 at 07:21:08 AM GMT 
//


package net.leadware.drools.server.model.configuration;

/*
 * #%L
 * DROOLS SERVER :: Model
 * $Id:$
 * $HeadURL:$
 * %%
 * Copyright (C) 2013 Leadware
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for KnowledgeAgentConfiguration complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="KnowledgeAgentConfiguration">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="knowledge-base-ref" type="{http://www.leadware.net/drools-server-configuration}KnowledgeBaseConfigurationRef"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="newInstance" type="{http://www.w3.org/2001/XMLSchema}boolean" fixed="false" />
 *       &lt;attribute name="scanDirectories" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="scanResources" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="scanPeriod" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" default="60" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "KnowledgeAgentConfiguration", namespace = "http://www.leadware.net/drools-server-configuration", propOrder = {
    "knowledgeBaseRef"
})
public class KnowledgeAgentConfiguration {

    @XmlElement(name = "knowledge-base-ref", namespace = "http://www.leadware.net/drools-server-configuration", required = true)
    protected KnowledgeBaseConfigurationRef knowledgeBaseRef;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "newInstance")
    protected Boolean newInstance;
    @XmlAttribute(name = "scanDirectories")
    protected Boolean scanDirectories;
    @XmlAttribute(name = "scanResources")
    protected Boolean scanResources;
    @XmlAttribute(name = "scanPeriod")
    @XmlSchemaType(name = "unsignedShort")
    protected Integer scanPeriod;

    /**
     * Gets the value of the knowledgeBaseRef property.
     * 
     * @return
     *     possible object is
     *     {@link KnowledgeBaseConfigurationRef }
     *     
     */
    public KnowledgeBaseConfigurationRef getKnowledgeBaseRef() {
        return knowledgeBaseRef;
    }

    /**
     * Sets the value of the knowledgeBaseRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link KnowledgeBaseConfigurationRef }
     *     
     */
    public void setKnowledgeBaseRef(KnowledgeBaseConfigurationRef value) {
        this.knowledgeBaseRef = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the newInstance property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isNewInstance() {
        if (newInstance == null) {
            return false;
        } else {
            return newInstance;
        }
    }

    /**
     * Sets the value of the newInstance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNewInstance(Boolean value) {
        this.newInstance = value;
    }

    /**
     * Gets the value of the scanDirectories property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isScanDirectories() {
        if (scanDirectories == null) {
            return true;
        } else {
            return scanDirectories;
        }
    }

    /**
     * Sets the value of the scanDirectories property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setScanDirectories(Boolean value) {
        this.scanDirectories = value;
    }

    /**
     * Gets the value of the scanResources property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isScanResources() {
        if (scanResources == null) {
            return true;
        } else {
            return scanResources;
        }
    }

    /**
     * Sets the value of the scanResources property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setScanResources(Boolean value) {
        this.scanResources = value;
    }

    /**
     * Gets the value of the scanPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getScanPeriod() {
        if (scanPeriod == null) {
            return  60;
        } else {
            return scanPeriod;
        }
    }

    /**
     * Sets the value of the scanPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setScanPeriod(Integer value) {
        this.scanPeriod = value;
    }

}
