//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.25 at 05:05:20 PM GMT 
//


package net.leadware.drools.server.model.configuration;

/*
 * #%L
 * DROOLS SERVER :: Model
 * $Id:$
 * $HeadURL:$
 * %%
 * Copyright (C) 2013 Leadware
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for KnowledgeSession complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="KnowledgeSession">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="knowledge-base" type="{http://www.leadware.net/drools-server-configuration}KnowledgeBase"/>
 *         &lt;element name="knowledge-agent" type="{http://www.leadware.net/drools-server-configuration}KnowledgeAgent"/>
 *       &lt;/choice>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="type" type="{http://www.leadware.net/drools-server-configuration}KnowledgeSessionType" default="STATELESS" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "KnowledgeSession", namespace = "http://www.leadware.net/drools-server-configuration", propOrder = {
    "knowledgeBase",
    "knowledgeAgent"
})
public class KnowledgeSession {

    @XmlElement(name = "knowledge-base", namespace = "http://www.leadware.net/drools-server-configuration")
    protected KnowledgeBase knowledgeBase;
    @XmlElement(name = "knowledge-agent", namespace = "http://www.leadware.net/drools-server-configuration")
    protected KnowledgeAgent knowledgeAgent;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "type")
    protected KnowledgeSessionType type;

    /**
     * Gets the value of the knowledgeBase property.
     * 
     * @return
     *     possible object is
     *     {@link KnowledgeBase }
     *     
     */
    public KnowledgeBase getKnowledgeBase() {
        return knowledgeBase;
    }

    /**
     * Sets the value of the knowledgeBase property.
     * 
     * @param value
     *     allowed object is
     *     {@link KnowledgeBase }
     *     
     */
    public void setKnowledgeBase(KnowledgeBase value) {
        this.knowledgeBase = value;
    }

    /**
     * Gets the value of the knowledgeAgent property.
     * 
     * @return
     *     possible object is
     *     {@link KnowledgeAgent }
     *     
     */
    public KnowledgeAgent getKnowledgeAgent() {
        return knowledgeAgent;
    }

    /**
     * Sets the value of the knowledgeAgent property.
     * 
     * @param value
     *     allowed object is
     *     {@link KnowledgeAgent }
     *     
     */
    public void setKnowledgeAgent(KnowledgeAgent value) {
        this.knowledgeAgent = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link KnowledgeSessionType }
     *     
     */
    public KnowledgeSessionType getType() {
        if (type == null) {
            return KnowledgeSessionType.STATELESS;
        } else {
            return type;
        }
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link KnowledgeSessionType }
     *     
     */
    public void setType(KnowledgeSessionType value) {
        this.type = value;
    }

}
