//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.01 at 01:41:36 PM GMT 
//


package net.leadware.drools.server.model.configuration;

/*
 * #%L
 * DROOLS SERVER :: Model
 * $Id:$
 * $HeadURL:$
 * %%
 * Copyright (C) 2013 - 2014 Leadware
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for KnowledgeBaseConfiguration complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="KnowledgeBaseConfiguration">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="resource-ref" type="{http://www.leadware.net/drools-server-configuration}ResourceConfigurationRef" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="onDuplicateRule" type="{http://www.leadware.net/drools-server-configuration}ResultSeverityConfiguration" default="INFO" />
 *       &lt;attribute name="onDuplicateFunction" type="{http://www.leadware.net/drools-server-configuration}ResultSeverityConfiguration" default="INFO" />
 *       &lt;attribute name="multiThreadEvaluation" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="maxEvaluationThreads" type="{http://www.w3.org/2001/XMLSchema}int" default="3" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "KnowledgeBaseConfiguration", namespace = "http://www.leadware.net/drools-server-configuration", propOrder = {
    "resourceRef"
})
public class KnowledgeBaseConfiguration {

    @XmlElement(name = "resource-ref", namespace = "http://www.leadware.net/drools-server-configuration", required = true)
    protected List<ResourceConfigurationRef> resourceRef;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "onDuplicateRule")
    protected ResultSeverityConfiguration onDuplicateRule;
    @XmlAttribute(name = "onDuplicateFunction")
    protected ResultSeverityConfiguration onDuplicateFunction;
    @XmlAttribute(name = "multiThreadEvaluation")
    protected Boolean multiThreadEvaluation;
    @XmlAttribute(name = "maxEvaluationThreads")
    protected Integer maxEvaluationThreads;

    /**
     * Gets the value of the resourceRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the resourceRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResourceRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ResourceConfigurationRef }
     * 
     * 
     */
    public List<ResourceConfigurationRef> getResourceRef() {
        if (resourceRef == null) {
            resourceRef = new ArrayList<ResourceConfigurationRef>();
        }
        return this.resourceRef;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the onDuplicateRule property.
     * 
     * @return
     *     possible object is
     *     {@link ResultSeverityConfiguration }
     *     
     */
    public ResultSeverityConfiguration getOnDuplicateRule() {
        if (onDuplicateRule == null) {
            return ResultSeverityConfiguration.INFO;
        } else {
            return onDuplicateRule;
        }
    }

    /**
     * Sets the value of the onDuplicateRule property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResultSeverityConfiguration }
     *     
     */
    public void setOnDuplicateRule(ResultSeverityConfiguration value) {
        this.onDuplicateRule = value;
    }

    /**
     * Gets the value of the onDuplicateFunction property.
     * 
     * @return
     *     possible object is
     *     {@link ResultSeverityConfiguration }
     *     
     */
    public ResultSeverityConfiguration getOnDuplicateFunction() {
        if (onDuplicateFunction == null) {
            return ResultSeverityConfiguration.INFO;
        } else {
            return onDuplicateFunction;
        }
    }

    /**
     * Sets the value of the onDuplicateFunction property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResultSeverityConfiguration }
     *     
     */
    public void setOnDuplicateFunction(ResultSeverityConfiguration value) {
        this.onDuplicateFunction = value;
    }

    /**
     * Gets the value of the multiThreadEvaluation property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isMultiThreadEvaluation() {
        if (multiThreadEvaluation == null) {
            return false;
        } else {
            return multiThreadEvaluation;
        }
    }

    /**
     * Sets the value of the multiThreadEvaluation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMultiThreadEvaluation(Boolean value) {
        this.multiThreadEvaluation = value;
    }

    /**
     * Gets the value of the maxEvaluationThreads property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getMaxEvaluationThreads() {
        if (maxEvaluationThreads == null) {
            return  3;
        } else {
            return maxEvaluationThreads;
        }
    }

    /**
     * Sets the value of the maxEvaluationThreads property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxEvaluationThreads(Integer value) {
        this.maxEvaluationThreads = value;
    }

}
