//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.24 at 06:38:19 PM WAT 
//


package net.leadware.drools.server.model.configuration;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.leadware.drools.server.model.configuration package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DroolsServer_QNAME = new QName("http://www.example.org/drools-server-configuration", "drools-server");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.leadware.drools.server.model.configuration
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DroolsServerConfiguration }
     * 
     */
    public DroolsServerConfiguration createDroolsServerConfiguration() {
        return new DroolsServerConfiguration();
    }

    /**
     * Create an instance of {@link KnowledgeAgent }
     * 
     */
    public KnowledgeAgent createKnowledgeAgent() {
        return new KnowledgeAgent();
    }

    /**
     * Create an instance of {@link Resource }
     * 
     */
    public Resource createResource() {
        return new Resource();
    }

    /**
     * Create an instance of {@link KnowledgeBase }
     * 
     */
    public KnowledgeBase createKnowledgeBase() {
        return new KnowledgeBase();
    }

    /**
     * Create an instance of {@link KnowledgeSession }
     * 
     */
    public KnowledgeSession createKnowledgeSession() {
        return new KnowledgeSession();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DroolsServerConfiguration }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/drools-server-configuration", name = "drools-server")
    public JAXBElement<DroolsServerConfiguration> createDroolsServer(DroolsServerConfiguration value) {
        return new JAXBElement<DroolsServerConfiguration>(_DroolsServer_QNAME, DroolsServerConfiguration.class, null, value);
    }

}
