//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.24 at 06:38:19 PM WAT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/drools-server-configuration", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package net.leadware.drools.server.model.configuration;
