//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.24 at 06:38:19 PM WAT 
//


package net.leadware.drools.server.model.configuration;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ResourceType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ResourceType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="DRL"/>
 *     &lt;enumeration value="XDRL"/>
 *     &lt;enumeration value="DSL"/>
 *     &lt;enumeration value="DSLR"/>
 *     &lt;enumeration value="DRF"/>
 *     &lt;enumeration value="DTABLE"/>
 *     &lt;enumeration value="BRL"/>
 *     &lt;enumeration value="PKG"/>
 *     &lt;enumeration value="PMML"/>
 *     &lt;enumeration value="XSD"/>
 *     &lt;enumeration value="DESCR"/>
 *     &lt;enumeration value="CHANGE_SET"/>
 *     &lt;enumeration value="BPMN"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ResourceType")
@XmlEnum
public enum ResourceType {

    DRL,
    XDRL,
    DSL,
    DSLR,
    DRF,
    DTABLE,
    BRL,
    PKG,
    PMML,
    XSD,
    DESCR,
    CHANGE_SET,
    BPMN;

    public String value() {
        return name();
    }

    public static ResourceType fromValue(String v) {
        return valueOf(v);
    }

}
