package  drools;

import net.leadware.drools.server.engine.test.engine.Agent;
import net.leadware.drools.server.engine.test.engine.ValidationResult;    
import java.util.List;

global ValidationResult result;
global List<Agent> agents;

rule "printrule_test_01" 
dialect "java"
when
    Agent($matricule : matricule);
then
    
    // On positionne le resultat
    result.setText("Le matricule de l'objet est vide");
    
    System.out.println("MATRICULE : " + $matricule);
end
